- hosts: pulsarservers
  pre_tasks:
    - name: Install some packages
      package:
        name:
          - build-essential
          - git
          - python3-dev
          - libcurl4-openssl-dev
          - libssl-dev
          - virtualenv
        state: present
        update_cache: yes
      become: yes
    - name: chown the /mnt dir to ubuntu
      file:
        path: /mnt
        owner: ubuntu
        group: ubuntu
        mode: 0755
      become: yes
  roles:
    - role: galaxyproject.nginx
      become: yes
    - galaxyproject.pulsar
