---

- name: Schedule garbage collection
  cron:
    name: cvmfs_gc_{{ item.1.repository }}
    cron_file: ansible_cvmfs_gc
    user: "{{ item.1.owner | default('root') }}"
    job: output=$(/usr/bin/cvmfs_server gc -f -t '1 Jan 1970 00:00:00' {{ item.1.repository }} 2>&1) || echo "$output"
    hour: 3
    minute: "{{ item.0 }}"
    weekday: 3
  with_indexed_items: "{{ cvmfs_repositories }}"
