---
galaxy_info:
  author: mtchavez and hexylena
  company: Galaxy Europe
  description: InfluxDB
  role_name: influxdb
  license: MIT
  min_ansible_version: 2.7
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: SLES
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
    - any
  - name: Debian
    versions:
    - all
  - name: EL
    versions:
    - all
  categories:
    - cloud
    - cloud:ec2
    - database
    - database:nosql
    - monitoring

dependencies: []
