---
# Manage config files

- name: Static config setup
  block:

    - name: Create Pulsar config dir
      file:
        state: directory
        path: "{{ pulsar_config_dir }}"
      notify:
        - "{{ pulsar_restart_handler_name | default('default restart pulsar handler') }}"

    - name: Create Pulsar app configuration file
      template:
        src: app.yml.j2
        dest: "{{ pulsar_config_dir }}/app.yml"
        mode: 0444
        backup: yes
      when: pulsar_yaml_config is defined
      notify:
        - "{{ pulsar_restart_handler_name | default('default restart pulsar handler') }}"

    - name: Create Pulsar job manager configuration file
      template:
        src: "job_managers.ini.j2"
        dest: "{{ pulsar_job_managers_config }}"
        mode: 0444
        backup: yes
      when: pulsar_job_managers is defined
      notify:
        - "{{ pulsar_restart_handler_name | default('default restart pulsar handler') }}"

    - name: Create additional Pulsar config files
      template:
        src: "{{ item }}.j2"
        dest: "{{ pulsar_config_dir }}/{{ item }}"
        mode: 0444
        backup: yes
      with_items:
        - server.ini
        - local_env.sh
        - job_metrics_conf.xml
        - dependency_resolvers_conf.xml
      notify:
        - "{{ pulsar_restart_handler_name | default('default restart pulsar handler') }}"

  remote_user: "{{ pulsar_remote_users.privsep | default(__pulsar_remote_user) }}"
  become: "{{ true if pulsar_become_users.privsep is defined else __pulsar_become }}"
  become_user: "{{ pulsar_become_users.privsep | default(__pulsar_become_user) }}"
