- name: Create group
  user:
    name: "{{ tiaas_group }}"
    state: present
  when: tiaas_create_group

- name: Create user account
  user:
    name: "{{ tiaas_user }}"
    comment: Training Infrastructure as a Service User
    group: "{{ tiaas_group }}"
    home: "{{ tiaas_dir }}"
  when: tiaas_create_user

- name: Ensure directory is available
  file:
    path: "{{ tiaas_dir }}"
    state: directory
    owner: "{{ tiaas_user }}"
    group: "{{ tiaas_group }}"
    mode: 0755

- name: Clone repository
  become: true
  become_user: "{{ tiaas_user }}"
  git:
    repo: "https://github.com/usegalaxy-eu/tiaas2"
    dest: "{{ tiaas_dir }}/code/"
    version: "{{ tiaas_version }}"
    force: "{{ tiaas_force_checkout }}"
  register: __tiaas_git_update_result
  notify: 'reload tiaas'

- name: Send runner script
  template:
    src: "run.sh"
    dest: "{{ tiaas_dir }}/run.sh"
    owner: "{{ tiaas_user }}"
    group: "{{ tiaas_group }}"
    mode: 0750
  notify: 'reload tiaas'

- name: Install base dependencies
  become: true
  become_user: "{{ tiaas_user }}"
  pip:
    requirements: "{{ tiaas_dir }}/code/requirements.txt"
    extra_args: "--index-url https://wheels.galaxyproject.org/simple/ --extra-index-url https://pypi.python.org/simple {{ pip_extra_args | default('') }}"
    virtualenv: "{{ tiaas_dir }}/venv/"
    virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
  environment:
    PYTHONPATH: null
    VIRTUAL_ENV: "{{ tiaas_dir }}/venv/"
  notify: 'reload tiaas'

- name: Ensure config directory is available
  file:
    path: "{{ tiaas_dir }}/config/"
    state: directory
    owner: "{{ tiaas_user }}"
    group: "{{ tiaas_group }}"
    mode: 0750

- name: Send config
  template:
    src: "config.py"
    dest: "{{ tiaas_dir }}/config/local_settings.py"
    owner: "{{ tiaas_user }}"
    group: "{{ tiaas_group }}"
    mode: 0750
  notify: 'reload tiaas'

- name: Install systemd unit file
  template:
    src: tiaas.service
    dest: /etc/systemd/system/tiaas.service
  notify: setup tiaas systemd

# Run syncdb on the application
- name: Update database
  become: true
  become_user: "{{ tiaas_user }}"
  django_manage:
    command: migrate
    app_path: "{{ tiaas_dir }}/code/"
    pythonpath: "{{ tiaas_dir }}"
    virtualenv: "{{ tiaas_dir }}/venv/"
  when: __tiaas_git_update_result is changed

# Create an initial superuser.
- name: Create superuser if needed
  become: true
  become_user: "{{ tiaas_user }}"
  django_manage:
    command: |
        shell -c "from django.contrib.auth.models import User; User.objects.create_superuser('{{ tiaas_admin_user }}', 'admin@localhost', '{{ tiaas_admin_pass }}')"
    app_path: "{{ tiaas_dir }}/code/"
    pythonpath: "{{ tiaas_dir }}"
    virtualenv: "{{ tiaas_dir }}/venv/"
  ignore_errors: yes

- name: Ensure static directory is available
  file:
    path: "{{ tiaas_dir }}/static/"
    state: directory
    owner: "{{ tiaas_user }}"
    group: "{{ tiaas_group }}"
    mode: 0755

- name: Collect static files
  become: true
  become_user: "{{ tiaas_user }}"
  django_manage:
    command: collectstatic
    app_path: "{{ tiaas_dir }}/code/"
    pythonpath: "{{ tiaas_dir }}"
    virtualenv: "{{ tiaas_dir }}/venv/"
  when: __tiaas_git_update_result is changed
